source "https://rubygems.org"

require "json"
require "open-uri"

# Getting the latest versions from GitHub for Jekyll/GitHub pages support.
versions = JSON.parse(URI("https://pages.github.com/versions.json").read)

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", versions["jekyll"]

# This is the default theme for new Jekyll sites. You may change this to anything you like.
#gem "minima", versions["minima"]

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
# gem "github-pages", versions["github-pages"], group: :jekyll_plugins
# gem "jekyll-include-cache", versions["jekyll-include-cache"], group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "github-pages", versions["github-pages"]
  gem "jekyll-feed", versions["jekyll-feed"]
  gem "jekyll-include-cache", versions["jekyll-include-cache"]
  gem "jekyll-paginate", versions["jekyll-paginate"]
  gem "jekyll-sitemap", versions["jekyll-sitemap"]
  gem "jekyll-gist", versions["jekyll-gist"]
  gem "jemoji", versions["jemoji"]
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1.2.10"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.2.0", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

gem "webrick", "~> 1.8"
